services:
  - type: web
    name: powerpulse
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BREVO_USER
        value: a5e3f1001@smtp-brevo.com
      - key: MONGO_URI
        value: mongodb+srv://josika886_db_user:0mTMsuHGgB2aPISK@powerpulse.fbwh8gh.mongodb.net/?appName=powerpulse
